Repository Uniminin/Ripple-Auto-Installer, pull requests merged in 2020-12, with the labels that each got.

#156 Bump to 2 | Fix all known issues [1]
  Main/config.sh
  Main/ripple.sh
  Main/ripple.sha1
  README.md
Labels: bug-fixes, enhancement, update

#157 S -> C [Letter]
  README.md
Labels: enhancement

#159 move RPRINT output -> stderr
  Main/tmux.sh
  Main/tmux.sha1
Labels: enhancement, update

#160 fix known issues & improve existing functionality
  Main/ripple.sh
  Main/ripple.sha1
Labels: bug-fixes, enhancement
